name=input("Welcome To Command prompt Whats Your Name?")
print(" ")
print("Hello" , name, ", How old are you?")
age=int(input())
nextAge= age + int(1)
print("So, on your next birthday you are", nextAge)
print(" ")
print("Now try these 3 examples:")
print(" ")
print("1. Imagine you have a shape, type the width and height. (Numbers only)")
print(" ")
width=input("     Enter a width:")
height=input("     Enter a height:")
area= int(width) * int(height)
print(" ")
print("The area of your shape is:", area)
print(" ")
print("2. Lets find out how many seconds are in a year.")
print(" ")
print("     How many seconds are in a minute?")
secondsPerMinute=int(input())
print("     How many minutes in a hour?")
minutesPerHour=int(input())
print("     How many hours are in a day?")
hoursPerDay=int(input())
print("     How many days are in a week?")
daysPerWeek=int(input())
print("     How many weeks are in a month? (Hint: 2+2)")
weeksPerMonth=int(input())
print("     Finally, how many months in a year?")
monthsPerYear=int(input())
secondsPerYear= secondsPerMinute * minutesPerHour * hoursPerDay * daysPerWeek * weeksPerMonth * monthsPerYear
print(" ")
print("There are", secondsPerYear ,"seconds in a year")
print(" ")
print("3. Now, try out these calculators.* (Write 1 number each)")
print("*each calculator can only add/minus/divide/multiply 2 numbers")
print(" ")
print("Addition calculator:")
nom1=input(".")
nom2=input(".")
answer1= int(nom1) + int(nom2)
print("The answer is", answer1)
print(" ")
print("Subtraction calculator:")
nom3=input(".")
nom4=input(".")
answer2= int(nom3) - int(nom4)
print("The answer is", answer2)
print(" ")
print("Division calculator:")
nom5=input(".")
nom6=input(".")
answer3= int(nom5) / int(nom6)
print("The answer is", answer3)
print(" ")
print("Multiplication calculator:")
nom7=input(".")
nom8=input(".")
answer4= int(nom7) * int(nom8)
print("The answer is", answer4)
print(" ")
print(" End. ")
print(" ")
print(" Python examples.\n"" By nop ")
